1:
  cross: [2, 2, 4, ""]
  tag_id: ["", 152, 142, 132]
2:
  cross: ["", 3, 1, 1]
  tag_id: [133, "", 153, 143]
3:
  cross: [2, "", 4, ""]
  tag_id: ["", 154, 144, 134]
4:
  cross: ["", 3, "", 1]
  tag_id: [135, "", 155, 145]