map:
  1:
    cross: [2, 2, 4, ""]
    tag_id: ["", 152, 142, 132]
  2:
    cross: ["", 3, 1, 1]
    tag_id: [133, "", 153, 143]
  3:
    cross: [2, "", 4, ""]
    tag_id: ["", 154, 144, 134]
  4:
    cross: ["", 3, "", 1]
    tag_id: [135, "", 155, 145]

state:
  1:
    prev:
      2: 152
      4: 132
  2:
    prev:
      1: 143
      3: 153
  3:
    prev:
      2: 154
      4: 134

  4:
    prev:
      1: 135
      3: 155



